### PR TITLE
 Easy Popsplit physics

### PR DESCRIPTION
**Pull request by Valdex**

### CODE REVIEW

**Comment by Gigabyte918** [comment]
@Valdex can you please add macros on your [Blob.io Edited](https://github.com/Valdex/BlobEdited)

**Comment by Valdex** [comment]
@Gigabyte918 done

**Comment by Gigabyte918** [comment]
@Valdex i saw you server based on agar.io mobile but i found something is not like mobile agar.io

**Comment by Valdex** [comment]
@Gigabyte918 i cant fix something

**Comment by Gigabyte918** [comment]
So its mean there is not way to make agar.io like physics in blob

**Pull request closed without merging**
